### ISSUE TITLE
Uncaught TypeError: Flux\Logger\Logger::escapeSDValue()

### ISSUE THREAD

**Issue by ThatBea** [fluxef/flux#2]
### Flux version(s) affected

5.13.1

### Description

When calling Flux\Logger\Logger::escapeSDValue() with a bool value it crashes with an Uncaught TypeError.

### How to reproduce

$bla=true;
$logger = new Flux\Logger\Logger();
$value=$logger->escapeSDValue($bla);

### Possible Solution

accept all possible types for escaping

**Comment by thataf** [comment]
confirmed. it's a bug.
