### ISSUE TITLE
Flux\Logger\Logger::escapeSDValue() truncates float decimal places

### ISSUE THREAD

**Issue by ThatBea** [fluxef/flux#3]
### Flux version(s) affected

5.13.1

### Description

When escaping a float value the decimal places are truncated.

### How to reproduce

```
$bla=47.11;
$logger = new Flux\Logger\Logger();
$value=$logger->escapeSDValue($bla);
```

$value should be "47.11" but is "47"

**Comment by thataf** [comment]
confirmed, it`s a bug.
